### ISSUE TITLE
Sync history and Sync diff don't work : Cannot read properties of null (reading 'listHistory')

### ISSUE THREAD

**Issue by cjunekim** [kometenstaub/obsidian-version-history-diff#12]
Hello

Show Git Diff view for active file works well without an issue. However, Show Sync history for active file and Show Sync diff view for active file don't work at all showing an empty window.

The developer's console shows the following error:

``
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'listHistory')
    at t.<anonymous> (app.js:1:1970557)
    at app.js:1:235078
    at Object.next (app.js:1:235183)
    at s (app.js:1:233922)
``

**Comment by cjunekim** [comment]
I am answering myself. Sync history and Sync diff seem to be related to the core plugin Sync, and if you don't use it, the result being empty is right -- however, it would be better to display some message instead, something like "Sync is not enabled" or so.

**Comment by kometenstaub** [comment]
Conditionally enabling these commands would probably make sense, yes.
